version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: dev_postgres_app
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: shop_db
    ports:
      - "5433:5432"
    volumes:
      - shop_data:/var/lib/postgresql/data
      # Tự động mount file init.sql vào thư mục khởi tạo của container
      - ./init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shop_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  shop_data:
    driver: local
